In [14]:
import pandas as pd
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3']})
df2 = df1.rename(columns={'A':'B'})
pd.concat([df1, df2], axis=1).set_index('A')

     B
A
A0  A0
A1  A1
A2  A2
A3  A3

In [18]:
import pandas as pd
gen2_vin = pd.read_csv("../data/vin/gen2-vin.csv", header = 1, names=["vin", "tcuid", "navi", "tcuid-sub", "navi-sub", "imp-date"],
                       dtype={'vin':'object', 'tcuid':'object', 'navi':'object', 'tcuid-sub':'object','navi-sub':'object',"imp-date":'object'})

gen2vv = gen2_vin[["vin", "tcuid", "navi", "tcuid-sub", "navi-sub"]]
gen2vvd = gen2vv[~gen2vv.duplicated()]
gen2vvd.to_csv("../data/vin/gen2-vin_all_201902.csv", index=False)
print("GEN2_ALL,{}".format(gen2vvd.shape[0]))

gen2_jp = gen2vvd[gen2vvd['tcuid-sub'].isin(["2044"])]
gen2_jp.to_csv("../data/vin/gen2-vin_jp_201902.csv", index=False)
print("GEN2_JP,{}".format(gen2_jp.shape[0]))

gen2_eu = gen2vvd[gen2vvd['tcuid-sub'].isin(["2035"])]
gen2_eu.to_csv("../data/vin/gen2-vin_eu_201902.csv", index=False)
print("GEN2_EU,{}".format(gen2_eu.shape[0]))

gen2_us = gen2vvd[gen2vvd['tcuid-sub'].isin(["2037"])]
gen2_us.to_csv("../data/vin/gen2-vin_us_201902.csv", index=False)
print("GEN2_US,{}".format(gen2_us.shape[0]))

gen2_ca = gen2vvd[gen2vvd['tcuid-sub'].isin(["2038"])]
gen2_ca.to_csv("../data/vin/gen2-vin_ca_201902.csv", index=False)
print("GEN2_CA,{}".format(gen2_ca.shape[0]))

gen2_other = gen2vvd[~gen2vvd['tcuid-sub'].isin(["2038", "2037", "2035", "2044"])]
gen2_other.to_csv("../data/vin/gen2-vin_other_201902.csv", index=False)
print("GEN2_OTHER,{}".format(gen2_other.shape[0]))

GEN2_ALL,291393
GEN2_JP,12717
GEN2_EU,32800
GEN2_US,4153
GEN2_CA,972
GEN2_OTHER,240751

In [19]:
gen1_vin = pd.read_csv("../data/vin/gen1-vin.csv", header = 1, names=["vin", "navi", "navi-sub", "imp-date"],
                       dtype={'vin':'object',  'navi':'object', 'navi-sub':'object',"imp-date":'object'})
gen1vv = gen1_vin[["vin", "navi", "navi-sub"]]
gen1vvd = gen1vv[~gen1vv.duplicated()]
gen1vvd.to_csv("../data/vin/gen1-vin_all_201902.csv", index=False)
print("GEN1_ALL,{}".format(gen1vvd.shape[0]))

gen1_jp = gen1vvd[gen1vvd['navi-sub'].isin(['0051','0056','0062','0074','0075'])]
gen1_jp.to_csv("../data/vin/gen1-vin_jp_201902.csv", index=False)
print("GEN1_JP,{}".format(gen1_jp.shape[0]))

gen1_eu = gen1vvd[gen1vvd['navi-sub'].isin(['1002','1028','1037','1049','1056'])]
gen1_eu.to_csv("../data/vin/gen1-vin_eu_201902.csv", index=False)
print("GEN1_EU,{}".format(gen1_eu.shape[0]))

gen1_us = gen1vvd[gen1vvd['navi-sub'].isin(['1001','1027','1047','1054'])]
gen1_us.to_csv("../data/vin/gen1-vin_us_201902.csv", index=False)
print("GEN1_US,{}".format(gen1_us.shape[0]))

gen1_ca = gen1vvd[gen1vvd['navi-sub'].isin(['1003','1029','1048','1055'])]
gen1_ca.to_csv("../data/vin/gen1-vin_ca_201902.csv", index=False)
print("GEN1_CA,{}".format(gen1_ca.shape[0]))

gen1_au = gen1vvd[gen1vvd['navi-sub'].isin(['1004','1030'])]
gen1_au.to_csv("../data/vin/gen1-vin_au_201902.csv", index=False)
print("GEN1_AU,{}".format(gen1_au.shape[0]))

gen1_other = gen1vvd[~gen1vvd['navi-sub'].isin(['0051','0056','0062','0074','0075','1001','1027','1047','1054','1002','1028','1037','1049','1056','1003','1029','1048','1055','1004','1030'])]
gen1_other.to_csv("../data/vin/gen1-vin_other_201902.csv", index=False)
print("GEN1_TOTHER,{}".format(gen1_other.shape[0]))

GEN1_ALL,62370
GEN1_JP,22201
GEN1_EU,31326
GEN1_US,7001
GEN1_CA,1491
GEN1_AU,351
GEN1_TOTHER,0

In [21]:
import pandas as pd
gen2k_vin = pd.read_csv("../data/vin/gen2k-vin.csv", header = 1, names=["vin", "tcuid", "navi", "tcuid-sub", "navi-sub", "imp-date"],
                       dtype={'vin':'object', 'tcuid':'object', 'navi':'object', 'tcuid-sub':'object','navi-sub':'object',"imp-date":'object'})

gen2kvv = gen2k_vin[["vin", "tcuid", "navi", "tcuid-sub", "navi-sub"]]
gen2kvvd = gen2kvv[~gen2kvv.duplicated()]
gen2kvvd.to_csv("../data/vin/gen2k-vin_all_201902.csv", index=False)
print("GEN2K_ALL,{}".format(gen2kvvd.shape[0]))

gen2k_jp = gen2kvvd[gen2kvvd['tcuid-sub'].isin(["2050"])]
gen2k_jp.to_csv("../data/vin/gen2k-vin_jp_201902.csv", index=False)
print("GEN2K_JP,{}".format(gen2k_jp.shape[0]))

gen2k_eu = gen2kvvd[gen2kvvd['tcuid-sub'].isin(["2049", "2053"])]
gen2k_eu.to_csv("../data/vin/gen2k-vin_eu_201902.csv", index=False)
print("GEN2K_EU,{}".format(gen2k_eu.shape[0]))

gen2k_us = gen2kvvd[gen2kvvd['tcuid-sub'].isin(["2047"])]
gen2k_us.to_csv("../data/vin/gen2k-vin_us_201902.csv", index=False)
print("GEN2K_US,{}".format(gen2k_us.shape[0]))

gen2k_other = gen2kvvd[~gen2kvvd['tcuid-sub'].isin(["2047", "2049", "2050", "2053"])]
gen2k_other.to_csv("../data/vin/gen2k-vin_other_201902.csv", index=False)
print("GEN2K_OTHER,{}".format(gen2k_other.shape[0]))

GEN2K_ALL,86581
GEN2K_JP,29166
GEN2K_EU,44112
GEN2K_US,13303
GEN2K_OTHER,0

In [59]:
import pandas as pd
import hashlib
gen2k_vin_02 = pd.read_csv("../data/vin/gen2k-vin.csv", header = 1, names=["vin", "tcuid", "navi", "tcuid-sub", "navi-sub", "imp-date"],
                       dtype={'vin':'object', 'tcuid':'object', 'navi':'object', 'tcuid-sub':'object','navi-sub':'object',"imp-date":'object'})
gen2k_vin_01 = pd.read_csv("../data/vin/gen2k_01_vin.csv", header = 1, names=["vin", "tcuid", "navi", "tcuid-sub", "navi-sub", "imp-date"],
                       dtype={'vin':'object', 'tcuid':'object', 'navi':'object', 'tcuid-sub':'object','navi-sub':'object',"imp-date":'object'})
#gen2k_vin = gen2k_vin.sort_values('vin')
gen2k_vin_02 = gen2k_vin_02[gen2k_vin_02['tcuid-sub'].isin(['2047'])]
gen2k_vin_01 = gen2k_vin_01[gen2k_vin_01['tcuid-sub'].isin(['2047'])]

gen2k_vin = pd.concat([gen2k_vin_01, gen2k_vin_02])
                           
def mkmd5(str):
    return hashlib.md5(str.encode('utf-8')).hexdigest()

In [60]:
from calendar import Calendar
cl = Calendar(firstweekday=6)

gen2k_vin_v = gen2k_vin[['vin']]
gen2k_vin_vd = gen2k_vin_v[~gen2k_vin_v.duplicated()]
gen2k_vin_vd["idx"] = gen2k_vin_vd['vin'].map(mkmd5)
gen2k_vin_vd = gen2k_vin_vd.set_index('idx')

gen2k_vin_v_01 = gen2k_vin_01[['vin']]
gen2k_vin_vd_01 = gen2k_vin_v_01[~gen2k_vin_v_01.duplicated()]
gen2k_vin_vd_01["idx"] = gen2k_vin_vd_01['vin'].map(mkmd5)
gen2k_vin_vd_01 = gen2k_vin_vd_01.rename(columns={'vin':'201901'})
gen2k_vin_vd_01 = gen2k_vin_vd_01.set_index('idx')

gen2k_vin_v_02 = gen2k_vin_02[['vin']]
gen2k_vin_vd_02 = gen2k_vin_v_02[~gen2k_vin_v_02.duplicated()]
gen2k_vin_vd_02["idx"] = gen2k_vin_vd_02['vin'].map(mkmd5)
gen2k_vin_vd_02 = gen2k_vin_vd_02.rename(columns={'vin':'201902'})
gen2k_vin_vd_02 = gen2k_vin_vd_02.set_index('idx')
#gen2k_vin_vi = gen2k_vin_v.rename(columns={'vin':'vini'})
#gen2k_vin_vv = pd.concat([gen2k_vin_v, gen2k_vin_vi], axis=1).set_index('vin')
#gen2k_vin_vd.head()

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [63]:
gen2k_vin_vd = pd.concat([gen2k_vin_vd, gen2k_vin_vd_01], axis=1)
for day in cl.itermonthdates(2019, 1):
    try:
        print(day.strftime("%Y%m%d"))
        cl_name = day.strftime("%Y%m%d")
        gen2k_vin_d = gen2k_vin[gen2k_vin['imp-date'].isin([cl_name])]
        gen2k_vin_dv = gen2k_vin_d[['vin']]
        gen2k_vin_dv = gen2k_vin_dv[~gen2k_vin_dv.duplicated()]
        gen2k_vin_dv['idx'] = gen2k_vin_dv['vin'].map(mkmd5)
        gen2k_vin_dv = gen2k_vin_dv.rename(columns={'vin':cl_name}).set_index('idx')
        #gen2k_vin_dv.head()
        #gen2k_vin_vvp = pd.concat([gen2k_vin_vvi,gen2k_vin_vv], axis=1)
        gen2k_vin_vd = pd.concat([gen2k_vin_vd, gen2k_vin_dv], axis=1)
    except:
        print("except:{}".format(day))
gen2k_vin_vd = pd.concat([gen2k_vin_vd, gen2k_vin_vd_02], axis=1)
for day in cl.itermonthdates(2019, 2):
    try:
        print(day.strftime("%Y%m%d"))
        cl_name = day.strftime("%Y%m%d")
        gen2k_vin_d = gen2k_vin[gen2k_vin['imp-date'].isin([cl_name])]
        gen2k_vin_dv = gen2k_vin_d[['vin']]
        gen2k_vin_dv = gen2k_vin_dv[~gen2k_vin_dv.duplicated()]
        gen2k_vin_dv['idx'] = gen2k_vin_dv['vin'].map(mkmd5)
        gen2k_vin_dv = gen2k_vin_dv.rename(columns={'vin':cl_name}).set_index('idx')
        #gen2k_vin_dv.head()
        #gen2k_vin_vvp = pd.concat([gen2k_vin_vvi,gen2k_vin_vv], axis=1)
        gen2k_vin_vd = pd.concat([gen2k_vin_vd, gen2k_vin_dv], axis=1)
    except:
        print("except:{}".format(day))
gen2k_vin_vd.head()

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.
d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  del sys.path[0]

20181230
20181231
20190101
20190102
20190103
20190104
20190105
20190106
20190107
20190108
20190109
20190110
20190111
20190112
20190113
20190114
20190115
20190116
20190117
20190118
20190119
20190120
20190121
20190122
20190123
20190124
20190125
20190126
20190127
20190128
20190129
20190130
20190131
20190201
20190202

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  app.launch_new_instance()
d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:28: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

20190127
20190128
20190129
20190130
20190131
20190201
20190202
20190203
20190204
20190205
20190206
20190207
20190208
20190209
20190210
20190211
20190212
20190213
20190214
20190215
20190216
20190217
20190218
20190219
20190220
20190221
20190222
20190223
20190224
20190225
20190226
20190227
20190228
20190301
20190302

,vin,201901,20181230,20181231,20190101,20190102,20190103,20190104,20190105,20190106,...,20190221,20190222,20190223,20190224,20190225,20190226,20190227,20190228,20190301,20190302
0000ddf079bc83ba11e7a21244cd8898,1N4AZ1CP8KC305634,1N4AZ1CP8KC305634,NaN,NaN,1N4AZ1CP8KC305634,1N4AZ1CP8KC305634,1N4AZ1CP8KC305634,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0004b30b81670c96c972fc94794bb7af,1N4AZ1CP6JC315268,1N4AZ1CP6JC315268,NaN,NaN,1N4AZ1CP6JC315268,1N4AZ1CP6JC315268,1N4AZ1CP6JC315268,1N4AZ1CP6JC315268,1N4AZ1CP6JC315268,1N4AZ1CP6JC315268,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
000de3805678a4cf0ce370d7f2d808ca,1N4AZ1CP6KC304904,1N4AZ1CP6KC304904,NaN,NaN,1N4AZ1CP6KC304904,NaN,1N4AZ1CP6KC304904,1N4AZ1CP6KC304904,1N4AZ1CP6KC304904,NaN,...,1N4AZ1CP6KC304904,1N4AZ1CP6KC304904,1N4AZ1CP6KC304904,1N4AZ1CP6KC304904,1N4AZ1CP6KC304904,1N4AZ1CP6KC304904,1N4AZ1CP6KC304904,1N4AZ1CP6KC304904,NaN,NaN
00174cd02c0389f41280be3431ac4570,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,NaN,NaN,NaN,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,...,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,1N4AZ1CP3JC303790,NaN,NaN
002a36f8b5a0c33d1629141f498d0755,1N4AZ1CP1JC306901,1N4AZ1CP1JC306901,NaN,NaN,NaN,NaN,NaN,NaN,1N4AZ1CP1JC306901,NaN,...,1N4AZ1CP1JC306901,1N4AZ1CP1JC306901,1N4AZ1CP1JC306901,1N4AZ1CP1JC306901,1N4AZ1CP1JC306901,1N4AZ1CP1JC306901,1N4AZ1CP1JC306901,1N4AZ1CP1JC306901,NaN,NaN

In [36]:
gen2k_vin_d = gen2k_vin[gen2k_vin['imp-date'].isin(["20190201"])]
gen2k_vin_dv = gen2k_vin_d[['vin']]
gen2k_vin_dv = gen2k_vin_dv[~gen2k_vin_dv.duplicated()]
gen2k_vin_dv['idx'] = gen2k_vin_dv['vin'].map(mkmd5)
gen2k_vin_dv = gen2k_vin_dv.rename(columns={'vin':'20190201'}).set_index('idx')
gen2k_vin_dv.head()
#gen2k_vin_vvp = pd.concat([gen2k_vin_vvi,gen2k_vin_vv], axis=1)
gen2k_vin_vd = pd.concat([gen2k_vin_vd, gen2k_vin_dv], axis=1)
gen2k_vin_vd.head()
#print(all.shape, gen2k_vin_dv.shape, gen2k_vin_dvd.shape)

d:\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

                                                vin           20190201
00012edc6e4846d47f5e08f1ec660940  SJNFAAZE1U0025871  SJNFAAZE1U0025871
00013d00654255bbffbbc8b17c7a2088  SJNFAAZE1U0052658                NaN
00015f554e17eecafaa72028c2428474  SJNFAAZE1U0049150                NaN
0001f77387de2997d59eec01a12c0438  SJNFAAZE1U0041820  SJNFAAZE1U0041820
00024e293982c801e1f0868fb1f07511  SJNFAAZE1U0020936  SJNFAAZE1U0020936

In [64]:
gen2k_vin_vd.to_csv("../data/vin/gen2k-vin_na_st.csv", index=False)